### ISSUE TITLE
Not working with iOS 17.2.1

### ISSUE THREAD

**Issue by alpipego** [CleanShare/Issues#1]
**Summary**  
it neither works with the built-in rules, nor any custom rules. 

**Steps to Reproduce**  
I tried to copy the URL both from Instagram and YouTube and the share ids were still there. 

**Expected Behavior**  
I expected the URL parameters to be removed. 

**Observed Behaviour**
They were not removed in the copied URL

**Metadata:**  
 - Device: iPhone 15 Pro 
 - OS: 17.2.1
 - App Version 1.0.5

**Comment by ptrkstr** [comment]
Thank you for raising this issue, I will investigate 🙏

**Comment by ptrkstr** [comment]
Could you also let me know how you copied the urls? (A number of ways to do it, app, browser, link from a thumbnail etc) a video would be helpful 🙏

**Comment by ptrkstr** [comment]
I tested it with instagram and it worked, did you include "www." for the custom instagram rule?
The instagram app uses www.
Here is a screenshot of what works.

![image](https://github.com/CleanShare/Issues/assets/11362913/49a31ef0-acfc-4c5e-a6d6-023c743e0a68)

I tested it with 17.2.1.

Could you let me know if that works for you?

**Comment by alpipego** [comment]
> I tested it with instagram and it worked, did you include "[www](http://www/)." for the custom instagram rule?
> The instagram app uses www.

Understood. I thought it would use the shortest possible match, i.e., `instagram.com` would match the `http` and `https` versions and all subdomains and `www.instagram.com` was only matching the `www` subdomain, etc.

> Could you also let me know how you copied the urls?

I use the `Copy (Without Tracking)` action. 

While adding the `www` to Instagram worked (I still think I would appreciate it if this was part of the built-in IG recipe), there is still an issue with YouTube, however.

https://github.com/CleanShare/Issues/assets/2003667/b2a1971c-f54a-40e8-813b-1c6d5c2b5396

**Comment by ptrkstr** [comment]
Thank you for the update ❤️ I'll add that feature in regarding ignoring the www part, great suggestion. I'll investigate the YouTube app issue, the video helps a lot, thank you so much.

**Comment by ptrkstr** [comment]
Before I add the ignoring of www, could you see any cases where a user would want to differentiate between www and without, and this change would disadvantage them? I don't think so but don't want to negatively impact any existing users if they do rely on it.

**Comment by ptrkstr** [comment]
I have submitted a build to the App Store for review which contains the following:
- 🐛 Update instagram query name (changed from 2023/11)
- 🎉 Ignore www. prefix
- 🐛 Fix Youtube links not being recognised

The Youtube issue was because Youtube provides its URL to extensions as `UTType.plainText` instead of `UTType.url` like other app do 🤷

**Comment by alpipego** [comment]
> Before I add the ignoring of www, could you see any cases where a user would want to differentiate between www and without, and this change would disadvantage them? I don't think so but don't want to negatively impact any existing users if they do rely on it.

I thought about this as well, and I don't think so. Maybe other subdomains on the host, but usually not the www and non-www versions.

> I have submitted a build to the App Store

Thank you. I'll keep my eyes peeled for an update on my phone.

**Comment by ptrkstr** [comment]
> I thought about this as well, and I don't think so. Maybe other subdomains on the host, but usually not the www and non-www versions.

Good points, will continue with ignoring it then 👍 

@alpipego before I release to the public, would you be able to test the TestFlight beta for me to check it's working how you're expecting? Here's a link to see it: https://testflight.apple.com/join/sId4iFsN

**Comment by alpipego** [comment]
Yes, great. I can confirm all three things work as expected. The description on the trigger field is also better than before. 🙏

**Comment by ptrkstr** [comment]
Thanks @alpipego, I've released 1.0.6 to the app store, will close the ticket. 
If there's a chance you'd consider revisiting your review, it would be highly appreciated 🙏
