### ISSUE TITLE
Remove trailing `?`

### ISSUE THREAD

**Issue by alpipego** [CleanShare/Issues#6]
When a share-id was the only parameter on a URL, the `?` remains in the cleaned URL. This can safely be removed, in my opinion.

![IMG_05CF6A965A7E-1](https://github.com/CleanShare/Issues/assets/2003667/4278abe9-5608-42b8-933d-ca44187bef7a)

**Comment by ptrkstr** [comment]
Great suggestion! Have submitted 1.0.7 to the app store that contains this 🙏
