### ISSUE TITLE
Support for Japanese localization

### ISSUE THREAD

**Issue by katagaki** [CleanShare/Issues#9]
**Is your feature request related to a problem? Please describe.**  

I have the share sheet set up with Copy and Copy (Without Tracking) on top of each other. Currently, the app is in English, which makes that look a little off when used on a device with Japanese localization set up.

**Describe the solution you'd like**  

I can provide Japanese localizations for the app. 

**Describe alternatives you've considered**  

N/A

**Additional context**  

N/A

**Comment by ptrkstr** [comment]
Thank you for raising this @katagaki, that sounds like an excellent idea 😍 I will respond when I have a language file ready for translation.

**Comment by ptrkstr** [comment]
@katagaki I've attached the japanese translation strings catalog. You will need a tool like Xcode 15 to be able to edit them.
When you open it, the sections needed translation would be:
- CleanShare/Shared/Resources/Localization/Localizble - * (everything here)
- CopyExtension/InfoPlist - CFBundleDisplayName (just the name used in the share sheet)

Once you're finished you could zip and reupload here, thank you so much 🙏 

[ja.xcloc.zip](https://github.com/CleanShare/Issues/files/15283816/ja.xcloc.zip)

**Comment by katagaki** [comment]
@ptrkstr 
Thank you for sharing the localization files!
Attached is the completed localization, which you can use in Clean Share.
Below the attached file are the localization notes, which you can refer to for my comments while localizing the files.

[ja-localized.xcloc.zip](https://github.com/CleanShare/Issues/files/15284680/ja-localized.xcloc.zip)

## Localization Notes
- `Localizable`
    - Error messages are localized to include a follow up instruction, to follow common conventions with error messages in Japanese.
    - `Cleaned URL` - localized to just `Success` in Japanese as it does not have a direct translation that works well in Japanese UI. An alternative is `リンクからトラッキングのパラメーターを除去しました` (lit. 'removed tracking parameters from the URL'), but it is a bit long.
    - `Confirm` - localized to `OK` which is used conventionally in Japanese UI.
    - `Hold Up!` - a similar level of casual text is usually not used in Japanese UI, so it has been changed to `ご確認をお願いします！` (lit. 'please check!').
    - `Query name` is generally localized to `パラメーター`, which means 'parameter' literally. This is to avoid confusion with the use of the term 'クエリー' (lit. 'query') in Japanese.
    - `Host` is generally localized to `ホストネーム`, which is more conventionally used when referring to the equivalent in English. `ホスト` (lit. 'list') can be ambiguous in Japanese.
- `CopyExtension/InfoPlist`
    - `Without Tracking` - localized to `トラッキングを無効化` (lit. 'disable tracking') to make it sound more natural. Another option would be `トラッキングを除去`, which means 'remove tracking' literally, but it may be ambiguous.
- Others
    - In Japanese UI, `トラッキング` refers to tracking in the context of the web, while `追跡` refers to tracking in the physical world.

**Comment by ptrkstr** [comment]
Thank you so much for the translations 🙏 I will integrate them now. 
I would like to give you credit in the help screen of the app, could I link to your github profile?
Something such as: "Japanese translation provided by [katagaki](https://github.com/katagaki)". 
If that sounds good, could you provide a translation for that as well? 😅

**Comment by katagaki** [comment]
@ptrkstr 

Thank you, that would be great! Please see the below text:

日本語の翻訳はkatagakiさんより提供しました。

**Comment by ptrkstr** [comment]
Thank you @katagaki, everything has been submitted to Apple and will be in the next 1.0.12 release.
If there are any issue with the translation feel free to reopen the ticket 🙏
